# 1. Context  
Suppose you are a DA in an e-wallet company, and you need to analyze the following datasets:  
* payment_report.csv (monthly payment volume of products)  
* product.csv (product information)  
* transactions.csv (transactions information)  

Statement: Understanding the situation of payment or transaction of an e-wallet company.

# EDA

## Import libraries

In [4]:
import pandas as pd
import numpy as np
from google.colab import drive

In [5]:
# import csv files
from google.colab import drive
drive.mount('/content/drive')

path_payment_report = '/content/drive/MyDrive/DAC K34/Python/Project_2/payment_report.csv'
path_product = '/content/drive/MyDrive/DAC K34/Python/Project_2/product.csv'
path_transactions = '/content/drive/MyDrive/DAC K34/Python/Project_2/transactions.csv'

payment_report = pd.read_csv(path_payment_report)
product = pd.read_csv(path_product)
transactions = pd.read_csv(path_transactions)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
# copy data set
df_payment_report = payment_report
df_product = product
df_transactions = transactions

Do EDA task:
-	Df payment_enriched (Merge payment_report.csv with product.csv)
-	Df transactions
Suggestions:
1.	Check each column: missing data? duplicates? incorrect data types?
2.	Summarize numerical data: any incorrect values?

Sample Answers:
- Incorrect data types: column A, column B -> Next step: No action/ Delete rows/…
- Incorrect values: column A, column B -> Next step: No action/ Delete rows/…
- Missing data: x rows in column A, y rows in column B -> Next step: No action/ Delete rows/…
- Duplicates: PK? x rows? -> Next step: No action/ Delete rows/…

## DataFrame df_payment_report

### Understand about data type / data value

In [7]:
df_payment_report.head()

# show rows and columns count
print(f'Rows count: {df_payment_report.shape[0]}\nColums count: {df_payment_report.shape[1]}')

# show data type
df_payment_report.info()

# further checking on columns
df_payment_report.shape
df_payment_report.describe()


Rows count: 919
Colums count: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   report_month   919 non-null    object
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64 
 3   source_id      919 non-null    int64 
 4   volume         919 non-null    int64 
dtypes: int64(3), object(2)
memory usage: 36.0+ KB


product_id   source_id        volume
count    919.000000  919.000000  9.190000e+02
mean    1192.517954   44.875952  1.978574e+08
std     1293.463329    0.910995  8.367595e+08
min        3.000000   37.000000  5.500000e+03
25%      640.000000   45.000000  1.250000e+06
50%     1059.000000   45.000000  7.982015e+06
75%     1585.000000   45.000000  5.447599e+07
max    15067.000000   45.000000  1.383171e+10

### Checking unique & missing values

In [10]:
# check null values
df_payment_report.isnull().sum()

# check unique values
## print the percentage of unique
num_unique = df_payment_report.nunique().sort_values()
print('---Percentage of unique values (%)---')
print(100/num_unique)

# check missing data
missing_value = df_payment_report.isnull().sum().sort_values(ascending = False)
missing_percent = df_payment_report.isnull().mean().sort_values(ascending = False)
print('')
print('---Number of missing values in each column---')
print(missing_value)
print('')
print('---Percentage of missing values (%)---')
if missing_percent.sum():
  print(missing_percent[missing_percent > 0] * 100)
else:
  print('None')

# check for duplicates
## show number of duplicated rows
print('')
print(f'Number of entirely duplicated rows: {df_payment_report.duplicated().sum()}')
## show all duplicated rows
df_payment_report[df_payment_report.duplicated()]

---Percentage of unique values (%)---
payment_group    50.000000
report_month     25.000000
source_id        25.000000
product_id        0.321543
volume            0.111607
dtype: float64

---Number of missing values in each column---
report_month     0
payment_group    0
product_id       0
source_id        0
volume           0
dtype: int64

---Percentage of missing values (%)---
None

Number of entirely duplicated rows: 0


Empty DataFrame
Columns: [report_month, payment_group, product_id, source_id, volume]
Index: []

- Incorrect data types: report_month -> Change to datetime data type
- Incorrect values: none -> No action
- Missing data: none -> No action
- Duplicates: report_month, payment_group, product_id, source_id, volume -> No action


### Handle missing values

There are no missing values.

### Handle duplicated data

There are no duplicated data.

## DataFrame df_product

### Understand about data type / data value

In [9]:
df_product.head()

# show rows and columns count
print(f'Rows count: {df_product.shape[0]}\nColums count: {df_product.shape[1]}')

# show data type
df_product.info()

# further checking on columns
df_product.shape
df_product.describe()


Rows count: 492
Colums count: 3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   product_id  492 non-null    int64 
 1   category    492 non-null    object
 2   team_own    492 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.7+ KB


product_id
count    492.000000
mean     862.886179
std     1015.964776
min        9.000000
25%      270.750000
50%      616.500000
75%     1419.250000
max    15067.000000

### Checking unique & missing values

In [11]:
# check null values
df_product.isnull().sum()

# check unique values
## print the percentage of unique
num_unique = df_product.nunique().sort_values()
print('---Percentage of unique values (%)---')
print(100/num_unique)

# check missing data
missing_value = df_product.isnull().sum().sort_values(ascending = False)
missing_percent = df_product.isnull().mean().sort_values(ascending = False)
print('')
print('---Number of missing values in each column---')
print(missing_value)
print('')
print('---Percentage of missing values (%)---')
if missing_percent.sum():
  print(missing_percent[missing_percent > 0] * 100)
else:
  print('None')

# check for duplicates
## show number of duplicated rows
print('')
print(f'Number of entirely duplicated rows: {df_product.duplicated().sum()}')
## show all duplicated rows
df_product[df_product.duplicated()]

---Percentage of unique values (%)---
team_own      33.333333
category       5.882353
product_id     0.203252
dtype: float64

---Number of missing values in each column---
product_id    0
category      0
team_own      0
dtype: int64

---Percentage of missing values (%)---
None

Number of entirely duplicated rows: 0


Empty DataFrame
Columns: [product_id, category, team_own]
Index: []

- Incorrect data types: none -> No action
- Incorrect values: none -> No action
- Missing data: none -> No action
- Duplicates: category, team_own -> No action


### Handle missing values

There are no missing values.

### Handle duplicated data

There are no duplicated data.

## DataFrame df_transactions

### Understand about data type / data value

In [12]:
df_transactions.head()

# show rows and columns count
print(f'Rows count: {df_transactions.shape[0]}\nColums count: {df_transactions.shape[1]}')

# show data type
df_transactions.info()

# further checking on columns
df_transactions.shape
df_transactions.describe()

Rows count: 1324002
Colums count: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324002 entries, 0 to 1324001
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype  
---  ------          --------------    -----  
 0   transaction_id  1324002 non-null  int64  
 1   merchant_id     1324002 non-null  int64  
 2   volume          1324002 non-null  int64  
 3   transType       1324002 non-null  int64  
 4   transStatus     1324002 non-null  int64  
 5   sender_id       1274943 non-null  float64
 6   receiver_id     1159207 non-null  float64
 7   extra_info      6095 non-null     object 
 8   timeStamp       1324002 non-null  int64  
dtypes: float64(2), int64(6), object(1)
memory usage: 90.9+ MB


transaction_id   merchant_id        volume     transType   transStatus  \
count    1.324002e+06  1.324002e+06  1.324002e+06  1.324002e+06  1.324002e+06   
mean     3.002233e+09  2.460318e+03  2.388059e+05  6.979222e+00 -1.204625e+01   
std      1.042606e+07  3.304277e+03  9.681009e+05  7.459714e+00  5.577823e+01   
min      3.000000e+09  5.000000e+00  1.000000e+00  2.000000e+00 -1.333000e+03   
25%      3.001121e+09  3.050000e+02  1.000000e+04  2.000000e+00  1.000000e+00   
50%      3.002200e+09  2.250000e+03  3.000000e+04  2.000000e+00  1.000000e+00   
75%      3.003255e+09  2.270000e+03  1.000000e+05  8.000000e+00  1.000000e+00   
max      6.000066e+09  1.625250e+05  7.869148e+07  3.000000e+01  1.000000e+00   

          sender_id   receiver_id     timeStamp  
count  1.274943e+06  1.159207e+06  1.324002e+06  
mean   1.033938e+08  2.084884e+08  1.683130e+12  
std    6.234305e+08  9.287794e+08  1.707815e+08  
min    1.000001e+07 -6.300000e+01  1.682874e+12  
25%    1.005657e+07  1.526700e+05  1.682994e+12  
50%    1.094193e+07  7.025130e+06  1.683097e+12  
75%    2.101266e+07  3.151238e+07  1.683269e+12  
max    6.993439e+09  2.100000e+10  1.683479e+12

### Checking unique & missing values

In [14]:
# check null values
df_transactions.isnull().sum()

# check unique values
## print the percentage of unique
num_unique = df_transactions.nunique().sort_values()
print('---Percentage of unique values (%)---')
print(100/num_unique)

# check missing data
missing_value = df_transactions.isnull().sum().sort_values(ascending = False)
missing_percent = df_transactions.isnull().mean().sort_values(ascending = False)
print('')
print('---Number of missing values in each column---')
print(missing_value)
print('')
print('---Percentage of missing values (%)---')
if missing_percent.sum():
  print(missing_percent[missing_percent > 0] * 100)
else:
  print('None')

# check for duplicates
## show number of duplicated rows
print('')
print(f'Number of entirely duplicated rows: {df_transactions.duplicated().sum()}')
## show all duplicated rows
df_transactions[df_transactions.duplicated()]

---Percentage of unique values (%)---
transType         14.285714
transStatus        2.857143
merchant_id        0.154799
extra_info         0.049092
volume             0.002021
sender_id          0.000576
receiver_id        0.000499
timeStamp          0.000076
transaction_id     0.000076
dtype: float64

---Number of missing values in each column---
extra_info        1317907
receiver_id        164795
sender_id           49059
transaction_id          0
merchant_id             0
transStatus             0
transType               0
volume                  0
timeStamp               0
dtype: int64

---Percentage of missing values (%)---
extra_info     99.539653
receiver_id    12.446733
sender_id       3.705357
dtype: float64

Number of entirely duplicated rows: 28


transaction_id  merchant_id  volume  transType  transStatus  \
149735       3000871152           75  193000          2            1   
149739       3000871161         2270   50000          2            1   
149753       3000687030         2250  165000          8            1   
149758       3000871242         2270  300000          2            1   
149762       3000871251            5     200         22            1   
251297       3000859278           60   50000          2         -217   
251307       3000859287           75   19300          2            1   
251345       3000853578         2895   25263          2            1   
251349       3000853584         6140   21622         22            1   
251353       3000853587         2270  500000          2            1   
251355       3000871197            5     400         22            1   
251360       3000669375         2250  100000          8            1   
459826       3000859323         6140    7076         22            1   
459832       3000847623            5     700         22            1   
459838       3000847632          305   10000          2            1   
459860       3000853623         8225  245027          2            1   
459865       3000853635          305   10000          2            1   
459868       3000853641           60  100000          2            1   
565943       3000876186         2270   10000          2            1   
565953       3000675189         2250    6000          8            1   
565971       3000859380          305  100000          2            1   
565975       3000859386           75   48250          2            1   
837468       3000859308         2250   20000          8            1   
837472       3000859314          305  100000          2            1   
1045769      3000876015          745  100000         30            1   
1045881      3000871119         7010    5900          2            1   
1045907      3000876303            5     300         22            1   
1045916      3000876327            5     200         22            1   

            sender_id   receiver_id extra_info      timeStamp  
149735   1.702717e+07           NaN        NaN  1682988617608  
149739   1.000935e+07  9.352000e+03        NaN  1682988617770  
149753   1.007484e+07  3.854830e+07        NaN  1682988623437  
149758   3.501383e+07  3.501383e+07        NaN  1682988625523  
149762   1.002801e+07  1.052919e+07        NaN  1682988626225  
251297   1.752038e+07  1.752038e+07        NaN  1683075010868  
251307   1.560510e+07  2.134597e+07        NaN  1683075013716  
251345   3.155863e+07           NaN        NaN  1683075020418  
251349   2.450001e+07  2.106593e+07        NaN  1683075020883  
251353   1.009376e+07  9.375800e+04        NaN  1683075021528  
251355   1.002801e+07  8.274000e+04        NaN  1683075021650  
251360   1.000116e+07  2.801112e+07        NaN  1683075022816  
459826   2.450001e+07  4.182500e+04        NaN  1683247817747  
459832   3.850001e+07  3.673782e+06        NaN  1683247820163  
459838   1.053447e+07  5.344710e+05        NaN  1683247821222  
459860   1.014136e+07           NaN        NaN  1683247826214  
459865   1.053503e+07  1.053503e+07        NaN  1683247826611  
459868   1.000332e+07  3.318000e+03        NaN  1683247826899  
565943   1.424667e+07  4.246669e+06        NaN  1683420609231  
565953   1.003888e+07  2.101640e+07        NaN  1683420610712  
565971   1.702837e+07  7.028371e+06        NaN  1683420625775  
565975   4.368219e+09  1.456485e+09        NaN  1683420626895  
837468   3.153879e+07  2.522800e+04        NaN  1683161415206  
837472   1.023464e+07  2.346400e+05        NaN  1683161416065  
1045769           NaN  3.726342e+09        NaN  1682902183161  
1045881  1.050709e+07  1.050709e+07        NaN  1682902213719  
1045907  1.002801e+07  3.155114e+07        NaN  1682902224983  
1045916  1.002801e+07  2.586542e+06        NaN  1682902226938

- Incorrect data types:

1.   timeStamp -> change to datetime data type
2.   sender_id -> change to int64 data type
3.   receiver_id -> change to int64 data type


- Incorrect values: none -> No action  

- Missing data:


1.   sender_id -> need to validate data with data provider/ fill up data according to extra_info (if available).
2.   receiver_id -> need to validate data with data provider/ fill up data according to extra_info (if available).
3.   extra_info -> need to validate data with data provider/ fill up data according to sender_id (if available).


- Duplicates: all columns -> No action

### Handle missing values

1.   sender_id
*   need to validate data with data provider/ fill up data according to extra_info (if available).

2.   receiver_id
*   need to validate data with data provider/ fill up data according to extra_info (if available).

3.   extra_info
*   need to validate data with data provider/ fill up data according to extra_info (if available).

### Handle duplicated data

As can see from the table above, there are 28 rows with duplicated data. They are from "extra_info" column and they are missing values. In this case, we will use method from "Handle missing values" part and no need to drop these rows.

## Xử lý Duplicate

## Tạo df payment_enriched (merge payment_report.csv with product.csv)

In [15]:
# tạo DataFramme payment_enriched
payment_enriched = df_payment_report.merge(df_product, on='product_id', how='left')
payment_enriched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   report_month   919 non-null    object
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64 
 3   source_id      919 non-null    int64 
 4   volume         919 non-null    int64 
 5   category       897 non-null    object
 6   team_own       897 non-null    object
dtypes: int64(3), object(4)
memory usage: 50.4+ KB


# Data Wrangling

*Using payment_report.csv & product.csv*

## 1/ Top 3 product_ids with the highest volume.

In [16]:
# df payment_report

# select product_id, sum(volume)
# from payment_report
# group by product_id
df_top_3 = df_payment_report.groupby('product_id')['volume'].sum().reset_index()

# order by volume DESC
df_top_3 = df_top_3.sort_values(by=['volume'], ascending=False)

# get top 3
df_top_3.head(3)


product_id       volume
279        1976  61797583647
43          429  14667676567
38          372  13713658515

## 2/ Given that 1 product_id is only owed by 1 team, are there any abnormal products against this rule?

In [17]:
# select distinct product_id, team_own
# from product
# group_by team_own
df_1_product_1_team = payment_enriched.groupby('product_id')['team_own'].nunique().reset_index()

# having count(distinct team_own) = 1
df_1_product_1_team[df_1_product_1_team['team_own'] != 1]

product_id  team_own
0             3         0
279        1976         0
308       10033         0

## 3/ Find the team has had the lowest performance (lowest volume) since Q2.2023. Find the category that contributes the least to that team.

In [18]:
# df payment_enriched

# select report_month, team_own, sum(volume)
# from payment_enriched
# where report_month >= 2023-04
# group by team_own, report_month

df_low = payment_enriched[payment_enriched['report_month'] >= '2023-04']
df_low

report_month payment_group  product_id  source_id       volume category  \
638      2023-04       payment           3         45         6000      NaN   
639      2023-04       payment          12         45    379013493  PXXXXXT   
640      2023-04       payment          15         45   2810487679  PXXXXXG   
641      2023-04       payment          17         45    489440838  PXXXXXB   
642      2023-04       payment          18         45   1261017518  PXXXXXB   
..           ...           ...         ...        ...          ...      ...   
914      2023-04       payment       15067         45      1504000  PXXXXXR   
915      2023-04        refund        1976         37   3542271587      NaN   
916      2023-04        refund        1976         38  13831708189      NaN   
917      2023-04        refund        1976         39   1905435543      NaN   
918      2023-04        refund        1976         39   3679922071      NaN   

    team_own  
638      NaN  
639      ASD  
640      ASD  
641      ASD  
642      ASD  
..       ...  
914      ASL  
915      NaN  
916      NaN  
917      NaN  
918      NaN  

[281 rows x 7 columns]

## 4/ Find the contribution of source_ids of refund transactions (payment_group = ‘refund’), what is the source_id with the highest contribution?

In [19]:
# select source_id, volume
# from payment_report
# where payment_group = 'refund'
# order by volume DESC
# lấy top 1

payment_report_refund = df_payment_report[payment_report.payment_group == 'refund']
payment_report_refund = payment_report_refund[['source_id','volume']].groupby(by=['source_id']).sum().reset_index().sort_values('volume', ascending=False)

payment_report_refund.head()

source_id       volume
1         38  36527454759
2         39  16119059662
0         37   9151069226

source_id 38 has the highest contribution.

*Using transactions.csv*

## 5/ Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions

In [20]:
def trans_type(row):
  # condition Bank Transfer tra cứu với transType và merchant_id
  ## chạy theo từng row của transType và merchant_id
  transType = row['transType']
  merchant_id = row['merchant_id']

  # chia thành 3 trường hợp transType = 2, transType = 8 và còn lại
  if transType == 2:
    if merchant_id == 1205:
      return 'Bank Transfer Transaction'
    elif merchant_id == 2260:
      return 'Withdraw Money Transaction'
    elif merchant_id == 2270:
      return 'Top Up Money Transaction'
    else:
      return 'Payment Transaction'
  elif transType == 8:
    if merchant_id == 2250:
      return 'Transfer Money Transaction'
    else:
      return 'Split Bill Transacion'
  else:
    return 'Invalid Transaction'

# áp dụng trans_type
df_transactions['transaction_type']=df_transactions.apply(trans_type, axis=1)
df_transactions.head()




transaction_id  merchant_id   volume  transType  transStatus   sender_id  \
0      3002692434            5   100000         24            1  10199794.0   
1      3002692437          305    20000          2            1  14022211.0   
2      3001960110         7255    48605         22            1         NaN   
3      3002680710         2270  1500000          2            1  10059206.0   
4      3002680713         2275    90000          2            1  10004711.0   

   receiver_id extra_info      timeStamp          transaction_type  
0     199794.0        NaN  1682932054455       Invalid Transaction  
1   14022211.0        NaN  1682932054912       Payment Transaction  
2   10530940.0        NaN  1682932055000       Invalid Transaction  
3      59206.0        NaN  1682932055622  Top Up Money Transaction  
4       4711.0        NaN  1682932056197       Payment Transaction

## 6/ Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers.

In [23]:
valid_transactions = transactions[transactions['transaction_type'] != 'Invalid Transaction']

valid_transactions

transaction_id  merchant_id   volume  transType  transStatus  \
1            3002692437          305    20000          2            1   
3            3002680710         2270  1500000          2            1   
4            3002680713         2275    90000          2            1   
5            3002680716         2270   200000          2            1   
6            3002680719           60   200000          2            1   
...                 ...          ...      ...        ...          ...   
1323996      3003602961         2250        1          8            1   
1323997      3003723030          305    20000          2            1   
1323998      3003723033         2270   100000          2            1   
1323999      3003723036         2270   100000          2            1   
1324001      3003602967         2250        1          8            1   

          sender_id  receiver_id extra_info      timeStamp  \
1        14022211.0   14022211.0        NaN  1682932054912   
3        10059206.0      59206.0        NaN  1682932055622   
4        10004711.0       4711.0        NaN  1682932056197   
5        10162232.0     162232.0        NaN  1682932056816   
6        10093450.0      93450.0        NaN  1682932057141   
...             ...          ...        ...            ...   
1323996  10310653.0   10558863.0        NaN  1683035671767   
1323997  24524311.0          NaN        NaN  1683035672634   
1323998  10277242.0     277242.0        NaN  1683035672876   
1323999  10144599.0     144599.0        NaN  1683035672892   
1324001  38559843.0   24501638.0        NaN  1683035673053   

                   transaction_type  
1               Payment Transaction  
3          Top Up Money Transaction  
4               Payment Transaction  
5          Top Up Money Transaction  
6               Payment Transaction  
...                             ...  
1323996  Transfer Money Transaction  
1323997         Payment Transaction  
1323998    Top Up Money Transaction  
1323999    Top Up Money Transaction  
1324001  Transfer Money Transaction  

[1103336 rows x 10 columns]

In [24]:
valid_transactions.groupby(by = 'transaction_type').agg(total_transactions=('transaction_id', 'nunique'),
                                                        total_volume=('volume', 'sum'),
                                                        sender_count=('sender_id', 'nunique'),
                                                        receiver_count=('receiver_id', 'nunique'))

total_transactions  total_volume  sender_count  \
transaction_type                                                             
Bank Transfer Transaction                37879   50605806190         23156   
Payment Transaction                     398665   71851515181        139583   
Split Bill Transacion                     1376       4901464          1323   
Top Up Money Transaction                290498  108606478829        110409   
Transfer Money Transaction              341173   37033171492         39021   
Withdraw Money Transaction               33725   23418181420         24814   

                            receiver_count  
transaction_type                            
Bank Transfer Transaction             9271  
Payment Transaction                 113298  
Split Bill Transacion                  572  
Top Up Money Transaction            110409  
Transfer Money Transaction           34585  
Withdraw Money Transaction           24814